//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSraRosaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_RECEPCION
    {
        public decimal DETALLE_RECEPCION_ID { get; set; }
        public decimal DETALLE_R_CANTIDAD { get; set; }
        public decimal DETALLE_R_PRECIO { get; set; }
        public decimal RECEPCION_PRODUCTO_ID { get; set; }
        public decimal PRODUCTO_ID { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual RECEPCION_PRODUCTO RECEPCION_PRODUCTO { get; set; }
    }
}
