//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSraRosaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COMPRA
    {
        public decimal DETALLE_COMPRA_ID { get; set; }
        public decimal ORDEN_COMPRA_ID { get; set; }
        public decimal HABITACION_NRO { get; set; }
        public decimal HUESPED_RUT { get; set; }
    
        public virtual HABITACION HABITACION { get; set; }
        public virtual HUESPED HUESPED { get; set; }
        public virtual ORDEN_COMPRA ORDEN_COMPRA { get; set; }
    }
}
